import { z } from 'zod';

export const loc = <T extends z.ZodTypeAny>(inner: T) =>
  z.object({ pt: inner, en: inner });

const locStr = loc(z.string());
const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'expected YYYY-MM-DD');
const navId = z.enum([
  'overview',
  'experiencia',
  'stack',
  'academics',
  'projetos',
  'contato',
]);
const sectionHeading = z.object({
  index: z.string(),
  title: locStr,
  subtitle: locStr,
});

const v2Schema = z.object({
  identity: z.object({
    name: locStr,
    brand: locStr,
    website: locStr,
    origin: locStr,
    languages: locStr,
    roleLine: locStr,
    coderLabel: locStr,
  }),
  navigation: z.object({
    menuLabel: locStr,
    closeLabel: locStr,
    heading: locStr,
    items: z.array(z.object({ id: navId, label: locStr })).length(6),
  }),
  global: z.object({
    available: locStr,
    availableForWork: locStr,
    portfolioSystem: locStr,
    copyright: locStr,
    version: locStr,
    languagePt: locStr,
    languageEn: locStr,
  }),
  accessibility: z.object({
    home: locStr,
    characterStudy: locStr,
    fallback3d: locStr,
  }),
  overview: z.object({
    eyebrow: locStr,
    selectedStack: locStr,
    worksTitle: locStr,
    moduleLabel: locStr,
    seeProject: locStr,
    initializeContact: locStr,
    availableProjects: locStr,
    figureCaption: locStr,
    annotations: locStr,
    frontEndTitle: locStr,
    frontEndItems: z.array(z.string()),
    cloudTitle: locStr,
    cloudItems: z.array(z.string()),
    dataTitle: locStr,
    dataItems: z.array(z.string()),
    responsiveStack: z.array(z.object({ label: locStr, value: z.string() })),
  }),
  sections: z.object({
    experience: sectionHeading,
    stack: sectionHeading.extend({ toolsLabel: locStr }),
    academics: sectionHeading.extend({
      formalEducation: locStr,
      previousDegree: locStr,
      certifications: locStr,
      seeCertificate: locStr,
    }),
    projects: sectionHeading,
    contact: sectionHeading,
  }),
  contact: z.object({
    directChannels: locStr,
    labels: z.object({
      email: locStr,
      website: locStr,
      github: locStr,
      linkedin: locStr,
      location: locStr,
    }),
    location: locStr,
    openToWork: locStr,
    availabilityCopy: locStr,
    responseTime: locStr,
    responseValue: locStr,
    subject: locStr,
    sendTransmission: locStr,
    subjectPlaceholder: locStr,
  }),
  characterStudy: z.object({
    metaTitle: locStr,
    metaDescription: locStr,
    breadcrumb: locStr,
    title: locStr,
    subtitle: locStr,
    figure: locStr,
    formatLabel: locStr,
    specificationTitle: locStr,
    specifications: z.array(z.object({ label: locStr, value: locStr })),
    modelReady: locStr,
    return: locStr,
    accessibleName: locStr,
    contextLost: locStr,
    reload: locStr,
  }),
  projectDetail: z.object({
    projectsLabel: locStr,
    selectedCaseStudy: locStr,
    overview: locStr,
    challenge: locStr,
    outcomes: locStr,
    projectImage: locStr,
    projectMedia: locStr,
    aspectRatio: locStr,
    specification: locStr,
    openRepository: locStr,
    contact: locStr,
  }),
});

export const portfolioSchema = z.object({
  v2: v2Schema,
  meta: z.object({
    title: locStr,
    description: locStr,
    openGraphDescription: locStr,
    nowUpdated: locStr,
    footer: locStr,
  }),
  flags: z.object({ showEducation: z.boolean(), showPhoto: z.boolean() }),
  nav: z.object({
    tools: locStr,
    exp: locStr,
    education: locStr,
    courses: locStr,
    projects: locStr,
    contact: locStr,
  }),
  sections: z.object({
    now: locStr,
    tools: locStr,
    exp: locStr,
    education: locStr,
    courses: locStr,
    projects: locStr,
    contact: locStr,
  }),
  hero: z.object({
    hello: locStr,
    role: locStr,
    summary: locStr,
    cta: locStr,
    techs: z.array(z.string()),
    links: z.object({
      email: z.string(),
      linkedin: z.string(),
      github: z.string(),
    }),
    photoUrl: z.string().nullable(),
  }),
  now: z.object({ items: z.array(locStr) }),
  tools: z.array(z.object({ name: locStr, items: locStr })),
  experience: z.array(
    z.object({
      company: z.string(),
      start: isoDate,
      end: isoDate.nullable(),
      periodLabel: locStr,
      employmentType: locStr,
      location: locStr,
      context: locStr,
      role: locStr,
      techs: z.array(z.string()),
      bullets: z.array(z.object({ head: locStr, text: locStr })),
    }),
  ),
  projects: z.array(
    z.object({
      imageUrl: z.string().nullable(),
      repoUrl: z.string().nullable(),
      title: locStr,
      dateLabel: locStr,
      desc: locStr,
      detail: z.object({
        category: locStr,
        challenge: locStr,
        outcomes: z.array(locStr),
        imageAlt: locStr,
        mediaHeader: locStr,
        mediaPlaceholder: locStr,
        figureCaption: locStr,
        mediaType: locStr,
        specifications: z.array(z.object({ k: locStr, v: locStr })),
      }),
      stack: z.array(z.object({ k: locStr, v: locStr })),
    }),
  ),
  projectsView: locStr,
  education: z.object({
    postgraduate: z.object({
      degree: locStr,
      school: locStr,
      period: locStr,
    }),
    degree: locStr,
    school: locStr,
    degreeYear: locStr,
    langLine: locStr,
    langCert: locStr,
  }),
  courses: z.array(
    z.object({
      title: locStr,
      issuer: locStr,
      year: z.string(),
      details: locStr.nullable(),
    }),
  ),
  form: z.object({
    name: locStr,
    email: locStr,
    message: locStr,
    send: locStr,
    cta: locStr,
    success: locStr,
    error: locStr,
  }),
});
